# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto']

    http_method_override: false
    handle_all_throwables: true

    php_errors:
        log: true

    validation:
        enabled: true

when@test:
    framework:
        test: true
