-- Generated by API/bin/generate-legacy-import.py - do not edit by hand.
-- Source: data/proglog.db
-- Prerequisites: migrations applied AND `app:seed-exercises` already run.

BEGIN;

DO $$ BEGIN
  IF (SELECT COUNT(*) FROM sessions) > 0 OR (SELECT COUNT(*) FROM workout_templates) > 0
     OR (SELECT COUNT(*) FROM measurements) > 0 THEN
    RAISE EXCEPTION 'Target database already contains data - refusing to import.';
  END IF;
  IF (SELECT COUNT(*) FROM exercises) = 0 THEN
    RAISE EXCEPTION 'Exercise catalog is empty - run app:seed-exercises first.';
  END IF;
END $$;

-- Profile (singleton, id = 1)
INSERT INTO profiles (id, sex, birth_date, default_rest_seconds, height_cm) VALUES (1, 'male', '1994-09-24', 120, 167.0)
ON CONFLICT (id) DO UPDATE SET sex = EXCLUDED.sex, birth_date = EXCLUDED.birth_date,
  default_rest_seconds = EXCLUDED.default_rest_seconds, height_cm = EXCLUDED.height_cm;

-- Workout templates
INSERT INTO workout_templates (id, name, sort_order, archived_at) VALUES ('00000000-0000-7254-ac96-b4e5181df001', 'Bodyweight', 0, NULL);

-- Template exercise lines
INSERT INTO template_exercises (id, template_id, exercise_id, sort_order, target_sets, target_reps, rest_seconds) VALUES ('00000000-0000-7c09-80cc-89d65e29f002', '00000000-0000-7254-ac96-b4e5181df001', (SELECT id FROM exercises WHERE name = 'Chin-Up'), 0, 3, 20, 180);
INSERT INTO template_exercises (id, template_id, exercise_id, sort_order, target_sets, target_reps, rest_seconds) VALUES ('00000000-0000-73c5-9e58-9b1cf5ade003', '00000000-0000-7254-ac96-b4e5181df001', (SELECT id FROM exercises WHERE name = 'Chest Push (single response)'), 1, 3, 50, 180);
INSERT INTO template_exercises (id, template_id, exercise_id, sort_order, target_sets, target_reps, rest_seconds) VALUES ('00000000-0000-74c9-8c37-5f05c6e0d004', '00000000-0000-7254-ac96-b4e5181df001', (SELECT id FROM exercises WHERE name = 'Bodyweight Squat'), 2, 3, 60, 180);

-- Sessions
INSERT INTO sessions (id, template_id, started_at, finished_at, notes) VALUES ('019ebc21-f463-7d4b-9e6b-2fb502284005', '00000000-0000-7254-ac96-b4e5181df001', '2026-06-12 16:00:02', '2026-06-12 16:02:54', NULL);
INSERT INTO sessions (id, template_id, started_at, finished_at, notes) VALUES ('019ebc79-c0c5-7794-ab03-7fb6bc119006', '00000000-0000-7254-ac96-b4e5181df001', '2026-06-12 17:35:56', '2026-06-12 17:47:33', NULL);

-- Session exercises
INSERT INTO session_exercises (id, session_id, exercise_id, sort_order, notes) VALUES ('00000000-0000-7fd2-8bdc-712afef57007', '019ebc21-f463-7d4b-9e6b-2fb502284005', (SELECT id FROM exercises WHERE name = 'Chin-Up'), 0, NULL);
INSERT INTO session_exercises (id, session_id, exercise_id, sort_order, notes) VALUES ('00000000-0000-7e20-b34b-c8bcb7c08008', '019ebc21-f463-7d4b-9e6b-2fb502284005', (SELECT id FROM exercises WHERE name = 'Chest Push (single response)'), 1, NULL);
INSERT INTO session_exercises (id, session_id, exercise_id, sort_order, notes) VALUES ('00000000-0000-7a51-85bd-9aab99108009', '019ebc21-f463-7d4b-9e6b-2fb502284005', (SELECT id FROM exercises WHERE name = 'Bodyweight Squat'), 2, NULL);
INSERT INTO session_exercises (id, session_id, exercise_id, sort_order, notes) VALUES ('00000000-0000-7934-be4b-28a72e2a800a', '019ebc79-c0c5-7794-ab03-7fb6bc119006', (SELECT id FROM exercises WHERE name = 'Chin-Up'), 0, NULL);
INSERT INTO session_exercises (id, session_id, exercise_id, sort_order, notes) VALUES ('00000000-0000-78fd-b0d5-2c7766de000b', '019ebc79-c0c5-7794-ab03-7fb6bc119006', (SELECT id FROM exercises WHERE name = 'Bodyweight Squat'), 2, NULL);
INSERT INTO session_exercises (id, session_id, exercise_id, sort_order, notes) VALUES ('00000000-0000-7374-b83d-19555807800c', '019ebc79-c0c5-7794-ab03-7fb6bc119006', (SELECT id FROM exercises WHERE name = 'Pushups'), 2, NULL);
INSERT INTO session_exercises (id, session_id, exercise_id, sort_order, notes) VALUES ('00000000-0000-781a-b383-40514125600d', '019ebc79-c0c5-7794-ab03-7fb6bc119006', (SELECT id FROM exercises WHERE name = 'Front Cable Raise'), 3, NULL);
INSERT INTO session_exercises (id, session_id, exercise_id, sort_order, notes) VALUES ('00000000-0000-7e6a-bb98-6e03a458a00e', '019ebc79-c0c5-7794-ab03-7fb6bc119006', (SELECT id FROM exercises WHERE name = 'Band Pull Apart'), 4, '');
INSERT INTO session_exercises (id, session_id, exercise_id, sort_order, notes) VALUES ('00000000-0000-7dfa-9ef8-ec53a1aca00f', '019ebc79-c0c5-7794-ab03-7fb6bc119006', (SELECT id FROM exercises WHERE name = 'Barbell Curl'), 5, NULL);
INSERT INTO session_exercises (id, session_id, exercise_id, sort_order, notes) VALUES ('00000000-0000-798c-854c-a2b9b0016010', '019ebc79-c0c5-7794-ab03-7fb6bc119006', (SELECT id FROM exercises WHERE name = 'Cable Rope Overhead Triceps Extension'), 6, NULL);
INSERT INTO session_exercises (id, session_id, exercise_id, sort_order, notes) VALUES ('00000000-0000-7f7e-b12f-652e4d09e011', '019ebc79-c0c5-7794-ab03-7fb6bc119006', (SELECT id FROM exercises WHERE name = 'Split Squats'), 7, NULL);

-- Set logs
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-72a1-a597-c2997ef85012', '00000000-0000-7fd2-8bdc-712afef57007', 1, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-72c2-a384-ecbc83572013', '00000000-0000-7fd2-8bdc-712afef57007', 2, 0.0, 8, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-727a-89b0-492a38468014', '00000000-0000-7fd2-8bdc-712afef57007', 3, 0.0, 6, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7035-8247-98501dc38015', '00000000-0000-7e20-b34b-c8bcb7c08008', 1, 0.0, 20, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7374-8770-f83f94889016', '00000000-0000-7e20-b34b-c8bcb7c08008', 2, 0.0, 15, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7431-b292-21e5cde48017', '00000000-0000-7e20-b34b-c8bcb7c08008', 3, 0.0, 13, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7f23-b5ed-46573b490018', '00000000-0000-7a51-85bd-9aab99108009', 1, 0.0, 20, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-77e4-b534-53a981697019', '00000000-0000-7a51-85bd-9aab99108009', 2, 0.0, 20, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7522-8939-1de6d1bca01a', '00000000-0000-7a51-85bd-9aab99108009', 3, 0.0, 20, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7738-be87-5072d3f6301b', '00000000-0000-7934-be4b-28a72e2a800a', 1, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-73f2-a87b-ef7d3108701c', '00000000-0000-7934-be4b-28a72e2a800a', 2, 0.0, 8, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7a7a-a8db-daf808cea01d', '00000000-0000-7934-be4b-28a72e2a800a', 3, 0.0, 6, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-76b1-b422-216ecdd4601e', '00000000-0000-78fd-b0d5-2c7766de000b', 1, 0.0, 20, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7569-b133-09844d1a001f', '00000000-0000-78fd-b0d5-2c7766de000b', 2, 0.0, 20, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-720e-80b6-b839d9072020', '00000000-0000-78fd-b0d5-2c7766de000b', 3, 0.0, 20, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-74cc-8984-a65dc82e3021', '00000000-0000-7374-b83d-19555807800c', 1, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7809-bcf6-9c212e511022', '00000000-0000-7374-b83d-19555807800c', 2, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7938-9289-cfa76f8fd023', '00000000-0000-7374-b83d-19555807800c', 3, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7894-8d27-3605266df024', '00000000-0000-781a-b383-40514125600d', 1, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7150-8c3d-ec247deab025', '00000000-0000-781a-b383-40514125600d', 2, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7064-a42b-ef1e91288026', '00000000-0000-781a-b383-40514125600d', 3, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7f08-8161-53bbacbc8027', '00000000-0000-7e6a-bb98-6e03a458a00e', 1, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7725-9070-6eb14fc06028', '00000000-0000-7e6a-bb98-6e03a458a00e', 2, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-74c5-ad8a-70bc951f8029', '00000000-0000-7e6a-bb98-6e03a458a00e', 3, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7ce4-b15e-ae675e95e02a', '00000000-0000-7dfa-9ef8-ec53a1aca00f', 1, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7e51-8f68-8ea44f5fa02b', '00000000-0000-7dfa-9ef8-ec53a1aca00f', 2, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-71d1-b9a9-da772fb8902c', '00000000-0000-7dfa-9ef8-ec53a1aca00f', 3, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-742a-a6e3-86540255402d', '00000000-0000-798c-854c-a2b9b0016010', 1, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7ac0-90c9-efff8ec9002e', '00000000-0000-798c-854c-a2b9b0016010', 2, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7c83-87de-3d25d1ac102f', '00000000-0000-798c-854c-a2b9b0016010', 3, 0.0, 10, FALSE, NULL);
INSERT INTO set_logs (id, session_exercise_id, set_number, weight_kg, reps, is_warmup, notes) VALUES ('00000000-0000-7c04-b33b-47ab831b0030', '00000000-0000-7f7e-b12f-652e4d09e011', 1, 0.0, 10, FALSE, NULL);

-- Measurements
INSERT INTO measurements (id, type, value, measured_at) VALUES ('019eb920-e000-7e99-83e5-59270511b031', 'bodyfat', 20.0, '2026-06-12 02:00:00');
INSERT INTO measurements (id, type, value, measured_at) VALUES ('019eb920-e000-7e3d-a5cb-8292c5114032', 'bodyfat', 19.9, '2026-06-12 02:00:00');
INSERT INTO measurements (id, type, value, measured_at) VALUES ('019eb920-e000-77e7-8301-b11ac1dc2033', 'neck', 37.0, '2026-06-12 02:00:00');
INSERT INTO measurements (id, type, value, measured_at) VALUES ('019eb920-e000-7ff8-88ac-3f6d110e4034', 'waist', 86.0, '2026-06-12 02:00:00');
INSERT INTO measurements (id, type, value, measured_at) VALUES ('019eb920-e000-7246-9d2b-c95b68931035', 'weight', 72.0, '2026-06-12 02:00:00');
INSERT INTO measurements (id, type, value, measured_at) VALUES ('019ec893-f400-7af7-9683-a8bcb4980036', 'bodyfat', 19.9, '2026-06-15 02:00:00');

-- Row-count verification: aborts the transaction on any mismatch.
DO $$ BEGIN
  IF (SELECT COUNT(*) FROM workout_templates) <> 1 THEN
    RAISE EXCEPTION 'workout_templates: expected 1, got %', (SELECT COUNT(*) FROM workout_templates);
  END IF;
  IF (SELECT COUNT(*) FROM template_exercises) <> 3 THEN
    RAISE EXCEPTION 'template_exercises: expected 3, got %', (SELECT COUNT(*) FROM template_exercises);
  END IF;
  IF (SELECT COUNT(*) FROM sessions) <> 2 THEN
    RAISE EXCEPTION 'sessions: expected 2, got %', (SELECT COUNT(*) FROM sessions);
  END IF;
  IF (SELECT COUNT(*) FROM session_exercises) <> 11 THEN
    RAISE EXCEPTION 'session_exercises: expected 11, got %', (SELECT COUNT(*) FROM session_exercises);
  END IF;
  IF (SELECT COUNT(*) FROM set_logs) <> 31 THEN
    RAISE EXCEPTION 'set_logs: expected 31, got %', (SELECT COUNT(*) FROM set_logs);
  END IF;
  IF (SELECT COUNT(*) FROM measurements) <> 6 THEN
    RAISE EXCEPTION 'measurements: expected 6, got %', (SELECT COUNT(*) FROM measurements);
  END IF;
END $$;

COMMIT;
